name: base
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Local Storage
  shared_preferences: ^2.2.0

  #Network
  dio: ^5.2.1+1
  url_launcher: ^6.1.11
  connectivity_plus: ^4.0.1
  flutter_html: ^3.0.0-alpha.6

  #State Management
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  file_picker: ^5.3.2

  #Localization
  intl: ^0.18.0

  #Animation
  lottie: ^2.4.0

  #Images
  flutter_svg: ^2.0.7
  image_picker: ^1.0.0

  #Firebase
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.0.0
  firebase_core: ^2.14.0
  firebase_analytics: ^10.4.3

  #Ui
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.5

  #timezones
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.2

   #Localizations
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  generate: true 
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/svgs/home/
    - assets/svgs/login/
    - assets/svgs/menu/
    - assets/svgs/intro/
    - assets/svgs/chat/
    - assets/jsons/

  fonts:
    - family: en
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: ar
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
    - family: IcoFont
      fonts:
        - asset: assets/fonts/icofont.ttf

