name: base
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Local Storage
  shared_preferences: ^2.2.2

  #Network
  dio: ^5.3.3
  url_launcher: ^6.2.1
  connectivity_plus: ^5.0.1
  flutter_html: ^3.0.0-alpha.6

  #State Management
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3

  #pick files
  file_picker: ^6.1.1

  #Localization
  intl: ^0.18.1

  #Animation
  lottie: ^2.7.0

  #Images
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4

  #Firebase
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.21.0
  firebase_analytics: ^10.6.3

  #Ui
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.6
  pin_code_fields: ^8.0.1

  #timezones
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.2

  #dart
  flutter_dotenv: ^5.1.0
  

   #Localizations
  flutter_localizations: 
    sdk: flutter
    version: ^0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  generate: true 
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/svgs/
    - assets/svgs/home/
    - assets/svgs/login/
    - assets/svgs/menu/
    - assets/svgs/intro/
    - assets/svgs/chat/
    - assets/json/
    - .env


  fonts:
    - family: en
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: ar
      fonts:
        - asset: assets/fonts/Montserrat-Arabic-Regular.ttf
    - family: IcoFont
      fonts:
        - asset: assets/fonts/icofont.ttf

