name: Build and Send APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4' # Adjust to your Flutter version

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release

      - name: upload
        id: upload_apk
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Artifact to Transfer.sh
        id: upload_artifact
        run: |
          UPLOAD_URL=$(curl --upload-file build/app/outputs/flutter-apk/app-release.apk https://transfer.sh/app-release.apk)
          echo "::set-output name=upload_url::$UPLOAD_URL"
      
      - name: Send APK URL via Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
        run: |
          MESSAGE="Here's the Flutter APK release: ${{ steps.upload_artifact.outputs.upload_url }}"
          curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"

    
 
  # send:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Send APK URL via Telegram
  #       env:
  #         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  #         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
  #       run: |
  #         MESSAGE="Here's the Flutter APK release: ${{ steps.upload_artifact.outputs.upload_url }}"
  #         curl -s "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"

# name: Build and Send APK

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.13.4' # Adjust to your Flutter version

#       - name: Build APK
#         run: |
#           flutter clean
#           flutter build apk --release

#       - name: Archive APK
#         uses: actions/upload-artifact@v2
#         with:
#           name: release-apk
#           path: build/app/outputs/flutter-apk/app-release.apk

#   send:
#     needs: build
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Download APK
#         uses: actions/download-artifact@v2
#         with:
#           name: release-apk
#           path: .

#       - name: Send APK via Telegram
#         env:
#           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#         run: |
#           curl -F chat_id=$TELEGRAM_CHAT_ID -F document=@app-release.apk "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument"

